#!/usr/bin/env perl
use Mojolicious::Lite -signatures;

plugin Config => {file => 'v073.conf'};

get '/' => sub ($c) {
    $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %> - V073</title></head>
  <body>
    <main><%= content %></main>
    <hr>
    <footer>
      Released as open source software under the MIT license<br>
      <a href="https://github.com/memowe/v073">V073 code @ GitHub</a>
    </footer>
  </body>
</html>
